### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mathisonian** [mathisonian/dimensionality-reduction#1]
What's left:

- [x] Add a third working slider to graphic two
- [x] Improve the static graphic in "The Project" section
- [x] Fix hover behavior on images
  - [x] Show image metadata on hover?
- [x] Create thumbnails of all the images
- [x] Finish writing copy
  - [x] bib as string, hacky
  - [x] pros and cons of each algo
  - [x] workshop title?
  - [x] workshop metadata title
  - [x] Get a snappier intro, I think we need at least a sentence of lead in before the art dataset is introduced
  - [x] Try to remove all the mathy use of "we ..."
  - [x] More engaging section headers? I like the "The X" but if we drop it they could be better.
  - [x] citations
- [x] add back "show details" button to math section
- [x] make sure intro / loading UX is good
- [x] mobile version (before public launch)
- [x] add analytics (before public launch)
- [x] consolidate colors for links, table, titles (I think we are using a yellow and an off orange together?)

/cc @fredhohman feel free to add to this list
